#+TITLE: Array-Oriented Computation of Electron Matrix Elements
#+OPTIONS: H:3 toc:t num:t 
#+LATEX_CLASS: article
#+LATEX_HEADER: \usepackage{braket, amsmath, amssymb, bbold, cleveref, tabularx} \usepackage[parfill]{parskip} \usepackage[a4paper, total={6in, 8in}]{geometry} \newcommand\numberthis{\addtocounter{equation}{1}\tag{\theequation}} 
#+LATEX_HEADER: \newenvironment{dummy}{}{}
#+LATEX_HEADER: \usepackage[toc,page]{appendix}
#+LATEX_HEADER: \usepackage{titlesec}
#+LATEX_HEADER: \usepackage[style=authoryear, backend=biber]{biblatex}
#+LATEX_HEADER: \addbibresource{/home/david/nextcloud/PHD/sources/references.bib}

* Theory

The non-relativistic electronic Hamiltonian can be expressed (denoting creators / annihilators by capital / small letters and employing the Einstein summation convention) as

$H = T_{ab} Ab + V_{ab} Ab + U_{abcd} ABcd$

where $T_{ab}, V_{ab}, U_{abcd}$ are the kinetic, nuclear and interaction matrix elements.

The non-orthonormality of the basis can be taken into account via the overlap matrix $S$ with elements

$\{A,b\} = S_{ab}$

Takaeta et al. (https://csclub.uwaterloo.ca/~pbarfuss/jpsj.21.2313.pdf) have derived non-recursive expressions for each of these
matrices in a Gaussian basis. These expressions can be recast in terms of SIMD-friendly array-oriented programming as to play nice with JAX.

Loosely speaking, this means turning loops to JAX builtins, such as matrix products and convolutions.

In the following, we denote integer division by $i / 2$ for an integer index $i$.

* Primitive and Contracted Matrix Elements

A basis vector $v_i$ of a Gaussian basis is represented by a linear combination of primitive Gaussians. A primitive Gaussian $p_i(\vec{\mu}, \sigma)$
is a "normal 3D Gaussian", characterized by mean and standard deviation.

$v_i = \sum_{j} c_{ij} p_j(\vec{\mu}, \sigma)$

Here, $v$ is called "contracted".

Consequently, the primitive and contracted one-electron matrix elements (a matrix with only two indices) are related by

$M_v = C M_p C^T$

And the two-electron matrix elements by

$U_v = C U_p C^T$

In the following, we discuss how to obtain array-oriented primitive matrix elements, suitable for promotion to contracted matrix elements.

* Overlap
The overlap matrix elements are given by

$a \cdot \prod_i \sum_I b_I(l_1, l_2, \vec{d}_{AP}, \vec{d}_{BP}, i) c_I$

where 

\begin{align*}
a &= \frac{\pi}{\gamma}^{3/2} e^{-\alpha_1 \alpha_2 \vec{d}_{AB}^2 / \gamma} \\
b &= f_{2i}(l_1, l_2,\vec{d}_{i, AP}, \vec{d}_{i, BP} ) \\
c_i &= \frac{(2i-1)!!}{(2 \gamma)^i} \\
f_j(l_1, l_2, a, b) &= \partial^j_x (a+x)^{l_1} (a+x)^{l_2} \vert_{x=0}
\end{align*}

* Kinetic
$\alpha_2 \cdot (2(l_2+m_2+n_2) + 3)S(l_2, m_2, n_2) - 2 \alpha_2^2(S(l_2+2,m_2,n_2) + S(l_2,m_2+2,n_2) + S(l_2,m_2,n_2+2)) - \frac{1}{2}( l_2(l_2-1)S(l_2-2, m_2, n_2) + m_2(m_2-2)S(l_2, m_2-2, n_2) + n_2(n_2 - 1)S(l_2, m_2, n_2-2))$

* Nuclear
The first group of nesting levels can be written as

$\sum_{ijk} A_i B_j C_k F_{i+j+k} = \sum_I F_I \sum_{i+j+k=I} A_i B_j C_k = \sum_I F_I \text{Conv}_3[A,B,C]_I$

where $\text{Conv}_3$ denotes the triple convolution operator

$\text{Conv}_3 : a,b,c \rightarrow \text{Conv}[\text{Conv}[a,b],c]$

The second group of nesting levels reads as

$A_I = \sum\limits_{i-2r-u = I, r \leq i /2, u \leq i/2 - r} a_i b_r c_{I, u}$

with


\begin{align*}
a_i &= i! (-1)^if_i \\
b_r(\epsilon) &= \frac{\epsilon^r}{r!} \\
\epsilon &= \gamma / 4 \\
c_{I, u}(p) &= \frac{p^{I - u}}{(I - u)!} \cdot f(u) \\
f(u) &= \frac{(-1)^u \epsilon^u}{u!}
\end{align*}

Where $p$ is the vector from the nucleus to the product center $CP$. This can be simplified by defining

\begin{align}
v_{2r} &= b_r \\
v_{2r + 1} &= 0
\end{align}

One obtains

$e_L = \sum\limits_{i - j = L, j \leq i} a_i v_j = \sum\limits_{i, L \geq 0}a_i v_{i - L} = v_{L, i} a_i$

And thus

$A_I = \sum\limits_{L - u = I, u \leq L / 2} e_L d_{L, u} = \sum\limits_{L} d'_{I, L} e_L$

Where

$d'_{I, L} = \frac{p^{2I - L} (-1)^{L - I} \epsilon^{L - I}}{(2I - L)!(L - I)!}$

is allowed non-zero entries only for $L/2 \geq L-I \geq 0$.

* Interaction

The first group of nesting levels can be written as

$\sum_{ijk} A_i B_j C_k F_{i+j+k} = \sum_I F_I \sum_{i+j+k=I} A_i B_j C_k = \sum_I F_I \text{Conv}_3[A,B,C]_I$

where $\text{Conv}_3$ denotes the triple convolution operator and $A, B, C$ correspond to $x, y, z$ quantities and $F_I = F(I, \overline{PQ}^2 / (\gamma_1 + \gamma_2))$

The second group of nesting levels reads as

$A_I = \sum\limits_{r_1 \leq i_1 / 2, r_2 \leq i_2 / 2, u  \leq (i_1 + i_2)/2 - r_1 - r_2}^{i_1 + i_2 - 2(r_1 + r_2) - u = I} a_{i_1, r_1} b_{i_2, r_2} d_{I + u, u}$, 

where 

\begin{align}
a_{i_1, r_1} &= \frac{f_{i_1} i_1!}{r_1! (i_1 - 2 r_1)! (4 \gamma_1)^{i_1 - r_1}} \\
b_{i_2, r_2} &= \frac{(-)^{i_2} f_{i_2} i_2!}{r_2! (i_2 - 2 r_2)! (4 \gamma_2)^{i_2 - r_2}} \\
d_{I + u, u} &= \frac{ (I + u)! (-)^u p_x^{I - u}}{u!(I-u)!\delta^{I}}
\end{align}

where $f_{i_1} = f(i_1, \overline{PA}_x, \overline{PB}_x), f_{i_2} = f(i_2, \overline{QC}_x, \overline{QD}_x)$ refers to the
binomial prefactors of the gaussian pairs with respect to their centers and $p_x$  is the center-center distance $Q-P$ and $\delta = \frac{1}{4 \gamma_1} + \frac{1}{4 \gamma_2}$. We now rewrite

\begin{align}
a_L &= \frac{1}{L!}\sum\limits_{r_1 \leq i_1 / 2}^{i_1 - 2r_1 = L} \frac{f_{i_1} i_1!}{(4 \gamma_1)^{i_1}} \frac{(4 \gamma_1)^{r_1}}{r_1!}\\
b_M &= \frac{1}{M!}\sum\limits_{r_2 \leq i_2 / 2}^{i_2 - 2r_2 = M} (-)^{i_2} \frac{f_{i_2} i_2!}{(4 \gamma_2)^{i_2}} \frac{(4 \gamma_2)^{r_2}}{r_2!} 
\end{align}

Due to the sums in the first and second line being restricted, they can not be directly translated to cross-correlations.
Instead, one can write

\begin{align}
v_{2r_1} &= \frac{1}{r_1! (4 \gamma_1)^{r_1}} \\
v_{2r_1 + 1} &= 0 \\
w_{i} &=  f_{i} i! (4 \gamma_1)^{i} 
\end{align}

To obtain

$a_L L! = \sum\limits_{j \leq i}^{i - j = L} w_{i} v_j = \sum\limits_{i, L \geq 0} w_{i} v_{i - L} \equiv \sum_i v_{L, i} w_i$

by promoting $v$ to a matrix. The rewriting for $b$ proceeds analogously. Then, defining 

\begin{align}
c_K &= \sum\limits_{L + M = K} a_L b_M = \text{Conv}[a, b]_K
\end{align}

we can write
$A_I = \sum\limits_{L + M - u = I} a_L b_M d_{I + u, u} = \sum\limits_{u \leq K}^{K - u = I} c_K d_{K, u} = \sum\limits_{I \geq 0}^{K} c_K d_{K, K - I} \equiv \sum\limits_{K} e_{I, K} c_K$
where 

$e_{I, K} &= \frac{ K! (-)^{K-I} p_x^{2I - K}}{(K-I)!(2I -K)!\delta^{I}}$

is allowed non-zero entries only for $K/2 \geq K-I \geq 0$.
